### ISSUE TITLE
numpy version assertion

### ISSUE THREAD

**Issue by dereneaton** [faircloth-lab/tapir#6]
I'm getting a numpy version error even though I'm using numpy v.1.10.2. I'm using the current pip-install (tapir v.1.0). It raised the following Exception:

```
assert numpy.version.version > '1.3', "tapir requires >= numpy 1.3"
```
It looks like the code is comparing strings when it should be comparing ints, i.e.,
```
'1.10' < '1.3'     ## returns false
```
Maybe something like the following would work, at least for any numpy v.1.x.y
```
version = int(numpy.__version__.split(".")[1])
assert version > 3, "tapir requires >= numpy 1.3"
```

**Comment by jonchang** [comment]
This was fixed in commit 2504cf5bb9bf, you can install the new version of tapir with

```
pip install -e git+https://github.com/faircloth-lab/tapir.git#egg=Package
```

I will update the README with this info.
