### ISSUE TITLE
issues in get_informative_sites routine in compute.py

### ISSUE THREAD

**Issue by singhal** [faircloth-lab/tapir#8]
The new version of DendroPy no longer supports a character matrix having an object called sequences.

I also am having issues with my JSON file having many 'null's throughout it which was throwing errors in parse_site_rates, but that might be user error with my version of HyPhy.

**Comment by jonchang** [comment]
Hi @singhal, thanks for reporting this issue. I can't seem to reproduce it; according to the [DendroPy source code](https://github.com/jeetsukumaran/DendroPy/blob/master/dendropy/datamodel/charmatrixmodel.py#L1109-L1119) the `sequences` attribute is alive and well in DendroPy. Can you please reinstall `tapir` using the instructions from the [README](https://github.com/faircloth-lab/tapir/blob/3544292ec18d8b93cd151045570b415531893e87/README.rst)? If you are still encountering the issue please copy and paste the full commands you are running as well as the data you're trying it on. You can also email me if you'd rather not post it publicly.

**Comment by singhal** [comment]
@jonchang Thanks for the help -- it looks like my Python was preferentially importing an older version of dendropy, so I changed the sys.path to import the newer version and all is set. Sorry for the distraction.

**Comment by jonchang** [comment]
No worries, glad to hear it's fixed.
